#!/usr/bin/env python3
"""
Alex Prime Report Generator
Generates PDF reports from workspace files
"""

import os
import datetime
from pathlib import Path

# Try to use reportlab for PDF generation
try:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.lib import colors
    HAS_REPORTLAB = True
except ImportError:
    HAS_REPORTLAB = False

WORKSPACE = Path("/home/ubuntu/.openclaw/workspace")
REPORTS_DIR = WORKSPACE / "reports"

def read_todo():
    """Read TODO.md and parse it"""
    todo_path = WORKSPACE / "TODO.md"
    if todo_path.exists():
        return todo_path.read_text()
    return "No TODO.md found"

def read_goals():
    """Read GOALS.md"""
    goals_path = WORKSPACE / "memory" / "GOALS.md"
    if goals_path.exists():
        return goals_path.read_text()
    return "No GOALS.md found"

def generate_text_report():
    """Generate a plain text report"""
    now = datetime.datetime.now(datetime.timezone.utc)
    date_str = now.strftime("%Y-%m-%d")
    time_str = now.strftime("%H:%M UTC")
    
    report = f"""
╔══════════════════════════════════════════════════════════════════╗
║                    ALEX PRIME STATUS REPORT                       ║
║                    {date_str} {time_str}                          ║
╚══════════════════════════════════════════════════════════════════╝

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                           TODO LIST
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

{read_todo()}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                         STRATEGIC GOALS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

{read_goals()}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                         SYSTEM STATUS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✅ Alex Prime: ONLINE
✅ Memory System: ACTIVE
✅ WhatsApp Inbound: WORKING
⚠️  WhatsApp Outbound: BLOCKED (same number)
⚠️  Web Search: NEEDS API KEY

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Report generated by Alex Prime
Your Executive Director Agent 🎯

"""
    return report

def main():
    """Main function"""
    now = datetime.datetime.now(datetime.timezone.utc)
    date_str = now.strftime("%Y-%m-%d")
    
    # Create reports directory
    report_dir = REPORTS_DIR / date_str
    report_dir.mkdir(parents=True, exist_ok=True)
    
    # Generate text report
    report_text = generate_text_report()
    
    # Save as text
    txt_path = report_dir / "ALEX_PRIME_STATUS.txt"
    txt_path.write_text(report_text)
    print(f"✅ Text report saved: {txt_path}")
    
    # Try to generate PDF if reportlab available
    if HAS_REPORTLAB:
        pdf_path = report_dir / "ALEX_PRIME_STATUS.pdf"
        doc = SimpleDocTemplate(str(pdf_path), pagesize=A4)
        styles = getSampleStyleSheet()
        story = []
        
        # Title
        title_style = ParagraphStyle(
            'Title',
            parent=styles['Heading1'],
            fontSize=24,
            spaceAfter=30,
            alignment=1  # Center
        )
        story.append(Paragraph("ALEX PRIME STATUS REPORT", title_style))
        story.append(Paragraph(f"{date_str}", styles['Normal']))
        story.append(Spacer(1, 20))
        
        # Content (simplified for PDF)
        for line in report_text.split('\n'):
            if line.strip():
                story.append(Paragraph(line, styles['Normal']))
            else:
                story.append(Spacer(1, 10))
        
        doc.build(story)
        print(f"✅ PDF report saved: {pdf_path}")
    else:
        print("ℹ️  reportlab not installed - PDF generation skipped")
        print("   Install with: pip install reportlab")
    
    return report_text

if __name__ == "__main__":
    main()
